name: AppIcon Generator

on:
  repository_dispatch:
    types: [generate-app-icon]
  workflow_dispatch:
    inputs:
      icon_source:
        description: 'Path to source icon file'
        required: true

jobs:
  generate-icons:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate App Icons
        uses: ka1ne/AppIcon@master
        with:
          icon_source: ${{ github.event.client_payload.icon_source || github.event.inputs.icon_source }}
          output_path: './Assets.xcassets/AppIcon.appiconset'
          icon_name: 'MyAppIcon'
          mac: 'true'
          watch: 'false'

      - name: Upload generated icons
        uses: actions/upload-artifact@v4
        with:
          name: AppIcon.appiconset
          path: './Assets.xcassets/AppIcon.appiconset'
        if: success()

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'AppIcon Generation Failed',
              body: 'The AppIcon generation webhook failed. Please check the logs for more information.'
            })
